language: node_js

stages:
  - compliance-tests
  - security-tests
  - unit-tests
  - quality-tests

matrix:
  fast_finish: true
  allow_failures:
    - script:
      - npm run security:outdated

jobs:
  include:
    - stage: compliance-tests
      script:
        - npx @commitlint/travis-cli

    - stage: compliance-tests
      script:
        - npm run compliance:lint

    - stage: security-tests
      script:
        - npm run security:outdated

    - stage: security-tests
      script:
        - npm run security:audit

    - stage: unit-tests
      script:
        - npm run tests:unit
